name: windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: env
        shell: bash
        run: |
          env

      - name: env (github)
        shell: bash
        run: |
          set -x
          github=$(mktemp)
          env |
            grep GITHUB_ |
            perl -pe 's/^/export /' > "$github"
          cat "$github"
          github2=$(cygpath -w "$github" | perl -pe 's#\\#\\\\#g')
          MSYS_NO_PATHCONV=1 /c/msys64/usr/bin/bash --noprofile --norc -eo pipefail -c ". $github2; env"

      - name: env (bash)
        shell: bash
        run: |
          /c/msys64/usr/bin/bash -eo pipefail -c 'env'

      - name: env (norc)
        shell: bash
        run: |
          PATH="/c/msys64/mingw64/bin:/c/msys64/usr/local/bin:/c/msys64/usr/bin:$PATH"
          /c/msys64/usr/bin/bash --norc -eo pipefail -c 'env'

      - name: env (noprofile, norc)
        shell: bash
        run: |
          PATH="/c/msys64/mingw64/bin:/c/msys64/usr/local/bin:/c/msys64/usr/bin:$PATH"
          /c/msys64/usr/bin/bash --noprofile --norc -eo pipefail -c 'env'
