name: windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: env
        shell: bash
        run: |
          env

      - name: env (github)
        shell: bash
        run: |
          set -x
          env |
            grep GITHUB_ |
            perl -pe 's/^/export /' > "input-env"
          /c/msys64/usr/bin/bash --noprofile --norc -eo pipefail ./test.sh
          ./test.sh
          ./test.pl

      - name: env (bash)
        shell: bash
        run: |
          /c/msys64/usr/bin/bash -eo pipefail -c 'env'

      - name: env (norc)
        shell: bash
        run: |
          PATH="/c/msys64/mingw64/bin:/c/msys64/usr/local/bin:/c/msys64/usr/bin:$PATH"
          /c/msys64/usr/bin/bash --norc -eo pipefail -c 'env'

      - name: env (noprofile, norc)
        shell: bash
        run: |
          PATH="/c/msys64/mingw64/bin:/c/msys64/usr/local/bin:/c/msys64/usr/bin:$PATH"
          /c/msys64/usr/bin/bash --noprofile --norc -eo pipefail -c 'env'
